package priv.wind.scheme.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import priv.wind.scheme.Beans.SchemeBean;

import priv.wind.scheme.data.SchemeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig schemeBeanDaoConfig;

    private final SchemeBeanDao schemeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        schemeBeanDaoConfig = daoConfigMap.get(SchemeBeanDao.class).clone();
        schemeBeanDaoConfig.initIdentityScope(type);

        schemeBeanDao = new SchemeBeanDao(schemeBeanDaoConfig, this);

        registerDao(SchemeBean.class, schemeBeanDao);
    }
    
    public void clear() {
        schemeBeanDaoConfig.clearIdentityScope();
    }

    public SchemeBeanDao getSchemeBeanDao() {
        return schemeBeanDao;
    }

}
